<?= $this->extend('main/layout') ?>
<?= $this->section('judul') ?>PO Barang Habis Pakai<?= $this->endSection('judul') ?>
<?= $this->section('isi') ?>
<?php $canInput=\App\Libraries\AccessControl::can('order.po_habis_pakai.input'); $canReceive=\App\Libraries\AccessControl::can('order.po_habis_pakai.receive'); ?>
<link rel="stylesheet" href="<?= base_url() ?>/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css"><script src="<?= base_url() ?>/plugins/datatables/jquery.dataTables.min.js"></script><script src="<?= base_url() ?>/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<div class="card"><div class="card-header"><ul class="nav nav-tabs"><li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#daftar"><i class="fas fa-list"></i> Daftar PO</a></li><?php if($canInput): ?><li class="nav-item"><a class="nav-link" data-toggle="tab" href="#buat"><i class="fas fa-plus"></i> Buat PO Baru</a></li><?php endif; ?><?php if($canReceive): ?><li class="nav-item"><a class="nav-link" data-toggle="tab" href="#terima"><i class="fas fa-truck"></i> Penerimaan Vendor</a></li><?php endif; ?></ul></div><div class="card-body"><div class="tab-content">
<div class="tab-pane fade show active" id="daftar"><table id="tblPoBhp" class="table table-bordered table-striped"><thead><tr><th>No</th><th>Nomor PO</th><th>Tanggal</th><th>Vendor</th><th>Qty PO</th><th>Diterima</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $i=>$r): ?><tr><td><?=$i+1?></td><td><?=esc($r['nomor_po'])?></td><td><?=esc($r['tanggal_po'])?></td><td><?=esc($r['supplier_nama'])?></td><td><?=number_format($r['total_qty'],2,',','.')?></td><td><?=number_format($r['total_diterima'],2,',','.')?></td><td><?=esc($r['status'])?></td></tr><?php endforeach; ?></tbody></table></div>
<?php if($canInput): ?><div class="tab-pane fade" id="buat"><form method="post" action="<?=site_url('poHabisPakai/simpan')?>"><div class="form-row"><div class="form-group col-md-3"><label>Tanggal PO</label><input type="date" name="tanggal_po" class="form-control" value="<?=date('Y-m-d')?>" required></div><div class="form-group col-md-5"><label>Supplier/Vendor</label><select name="supplier_id" class="form-control" required><option value="">-- pilih --</option><?php foreach($suppliers as $s): ?><option value="<?=$s['supid']?>"><?=esc($s['supnama'])?></option><?php endforeach; ?></select></div><div class="form-group col-md-4"><label>Catatan</label><input name="catatan" class="form-control"></div></div><table class="table table-bordered"><thead><tr><th>Barang</th><th>Satuan</th><th>Qty Pesan</th><th>Harga</th></tr></thead><tbody><?php foreach($stok as $s): ?><tr><td><?=esc($s['nama'])?><input type="hidden" name="stok_id[]" value="<?=$s['id']?>"></td><td><?=esc($s['satuan'])?></td><td><input type="number" name="qty_pesan[]" class="form-control" min="0" step="0.01" value="0"></td><td><input type="number" name="harga[]" class="form-control" min="0" step="0.01" value="0"></td></tr><?php endforeach; ?></tbody></table><button class="btn btn-primary">Simpan PO Barang Habis Pakai</button></form></div><?php endif; ?>
<?php if($canReceive): ?><div class="tab-pane fade" id="terima"><p class="text-muted">Hanya PO yang dibuat melalui modul ini yang tampil. Stok bertambah setelah qty diterima dan nomor Invoice dicatat.</p><table id="tblTerimaBhp" class="table table-bordered table-striped"><thead><tr><th>PO</th><th>Vendor</th><th>Barang</th><th>Sisa</th><th>Aksi</th></tr></thead><tbody><?php foreach($details as $d): ?><tr><td><?=esc($d['nomor_po'])?></td><td><?=esc($d['supplier_nama'])?></td><td><?=esc($d['nama'])?><br><small><?=esc($d['kode'])?> (<?=esc($d['satuan'])?>)</small></td><td><?=number_format((float)$d['qty_pesan']-(float)$d['qty_diterima'],2,',','.')?></td><td><form method="post" action="<?=site_url('poHabisPakai/terima')?>" class="form-inline"><input type="hidden" name="detail_id" value="<?=$d['id']?>"><input class="form-control form-control-sm mr-1" style="width:90px" type="number" name="qty" min="0.01" max="<?= (float)$d['qty_pesan']-(float)$d['qty_diterima']?>" step="0.01" value="<?= (float)$d['qty_pesan']-(float)$d['qty_diterima']?>" required><input class="form-control form-control-sm mr-1" style="width:140px" name="nomor_invoice" placeholder="No. Invoice" required><input class="form-control form-control-sm mr-1" style="width:140px" name="nomor_surat_jalan" placeholder="No. Surat Jalan"><button class="btn btn-sm btn-primary">Terima</button></form></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
</div></div></div><script>$(function(){$('#tblPoBhp,#tblTerimaBhp').DataTable({pageLength:10,lengthChange:false,order:[[2,'desc']]});});</script>
<?= $this->endSection('isi') ?>
