<?= $this->extend('main/layout') ?>
<?= $this->section('judul') ?><?= $header ? 'Edit' : 'Input' ?> Produk Sample Customer<?= $this->endSection('judul') ?>
<?= $this->section('subjudul') ?><a class="btn btn-warning" href="<?= site_url('barangkeluar/data#sample') ?>"><i class="fa fa-undo"></i> Kembali ke Pengiriman</a><?= $this->endSection('subjudul') ?>
<?= $this->section('isi') ?>
<?php if ($message = session()->getFlashdata('error')) : ?><div class="alert alert-danger"><?= esc($message) ?></div><?php endif ?>
<form method="post" action="<?= site_url('sampleproduk/simpan') ?>" id="sampleForm">
<?= csrf_field() ?><input type="hidden" name="faktur_lama" value="<?= esc($header['faktur'] ?? '') ?>">
<div class="card"><div class="card-header"><strong>Surat Jalan Sample</strong><small class="d-block text-muted">Sample dapat dikaitkan ke PO customer. Qty sample akan dihitung sebagai bagian dari PO, sehingga pengiriman berikutnya hanya mengambil sisa PO dan invoice dapat memilih surat jalan sample.</small></div><div class="card-body">
<div class="form-row"><div class="form-group col-md-4"><label>No Surat Jalan</label><input name="faktur" class="form-control" required value="<?= esc($header['faktur'] ?? 'SAMPLE-' . date('YmdHis')) ?>"></div><div class="form-group col-md-4"><label>Tanggal</label><input type="date" name="tanggal" class="form-control" required value="<?= esc($header['tglfaktur'] ?? date('Y-m-d')) ?>"></div><div class="form-group col-md-4"><label>Customer</label><select name="pelanggan" class="form-control" required><option value="">-- Pilih Customer --</option><?php foreach ($pelanggan as $p) : ?><option value="<?= (int) $p['pelid'] ?>" <?= (int)($header['idpel'] ?? 0) === (int)$p['pelid'] ? 'selected' : '' ?>><?= esc($p['pelnama']) ?></option><?php endforeach ?></select></div></div>
<div class="form-row"><div class="form-group col-md-4"><label>Gudang Asal</label><select name="gudang" class="form-control" required><option value="">-- Pilih Gudang --</option><?php foreach ($gudang as $g) : ?><option value="<?= (int) $g['gdgid'] ?>" <?= (int)($header['gudang'] ?? 0) === (int)$g['gdgid'] ? 'selected' : '' ?>><?= esc($g['gdgnama']) ?></option><?php endforeach ?></select></div></div>
<hr><div id="items"><?php $formRows = $details ?: [['detbrgkode' => '', 'detjml' => 1, 'detpo' => '']]; foreach ($formRows as $detail) : $kodeDetail = (string)($detail['detbrgkode'] ?? ''); $options = $poByProduct[$kodeDetail] ?? []; ?><div class="form-row item-row"><div class="form-group col-md-5"><label>Produk</label><select name="kode[]" class="form-control product-select" required><option value="">-- Pilih Produk --</option><?php foreach ($produk as $p) : ?><option value="<?= esc($p['brgkode']) ?>" <?= $kodeDetail === (string)$p['brgkode'] ? 'selected' : '' ?>><?= esc($p['brgkode'] . ' - ' . $p['brgnama']) ?></option><?php endforeach ?></select></div><div class="form-group col-md-4"><label>PO Customer <small class="text-muted">(opsional)</small></label><select name="po_no[]" class="form-control po-select"><option value="">-- Sample tanpa PO --</option><?php foreach ($options as $po) : ?><option value="<?= esc($po['detnopo']) ?>" <?= (string)($detail['detpo'] ?? '') === (string)$po['detnopo'] ? 'selected' : '' ?>><?= esc($po['detnopo']) ?> — sisa <?= number_format((float)($po['detkurang'] ?? 0), 0, ',', '.') ?></option><?php endforeach ?></select></div><div class="form-group col-md-2"><label>Qty</label><input type="number" name="qty[]" min="1" step="1" class="form-control" required value="<?= (int)($detail['detjml'] ?? 1) ?>"></div><div class="form-group col-md-1"><label>&nbsp;</label><button type="button" class="btn btn-danger form-control remove-row"><i class="fa fa-trash"></i></button></div></div><?php endforeach ?></div><button type="button" class="btn btn-secondary" id="addRow"><i class="fa fa-plus"></i> Tambah Produk</button></div><div class="card-footer text-right"><button class="btn btn-primary"><i class="fa fa-save"></i> Simpan Surat Jalan</button></div></div></form>
<script>
const poByProduct = <?= json_encode($poByProduct ?? [], JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP) ?>;
function refreshPoOptions(row) { const product = row.querySelector('.product-select').value; const select = row.querySelector('.po-select'); const selected = select.value; select.innerHTML = '<option value="">-- Sample tanpa PO --</option>'; (poByProduct[product] || []).forEach(po => { const option = document.createElement('option'); option.value = po.detnopo; option.textContent = po.detnopo + ' — sisa ' + Number(po.detkurang || 0).toLocaleString('id-ID'); option.selected = po.detnopo === selected; select.appendChild(option); }); }
document.getElementById('items').addEventListener('change', e => { if (e.target.classList.contains('product-select')) refreshPoOptions(e.target.closest('.item-row')); });
document.getElementById('addRow').addEventListener('click', () => { const row = document.querySelector('.item-row').cloneNode(true); row.querySelector('.product-select').selectedIndex = 0; row.querySelector('.po-select').innerHTML = '<option value="">-- Sample tanpa PO --</option>'; row.querySelector('input').value = 1; document.getElementById('items').appendChild(row); });
document.getElementById('items').addEventListener('click', e => { const btn = e.target.closest('.remove-row'); if (btn && document.querySelectorAll('.item-row').length > 1) btn.closest('.item-row').remove(); });
</script>
<?= $this->endSection('isi') ?>