<?php
namespace App\Controllers;
use App\Libraries\AccessControl;
use App\Models\ModelDetailPoHabisPakai;
use App\Models\ModelPenerimaanPoHabisPakai;
use App\Models\ModelPoHabisPakai;
use App\Models\ModelStokHabisPakai;
use App\Models\ModelSupplier;
use App\Models\ModelLogStokHabisPakai;
class PoHabisPakai extends BaseController
{
    public function index(){ if(!AccessControl::can('order.po_habis_pakai.view'))return $this->deny(); $db=db_connect(); $rows=$db->table('po_habis_pakai p')->select('p.*,COALESCE(SUM(d.qty_pesan),0) total_qty,COALESCE(SUM(d.qty_diterima),0) total_diterima')->join('po_habis_pakai_detail d','d.po_id=p.id','left')->groupBy('p.id')->orderBy('p.tanggal_po','DESC')->orderBy('p.id','DESC')->get()->getResultArray(); $details=$db->table('po_habis_pakai_detail d')->select('d.*,p.nomor_po,p.supplier_nama')->join('po_habis_pakai p','p.id=d.po_id')->where('d.qty_diterima < d.qty_pesan',null,false)->orderBy('p.tanggal_po','DESC')->get()->getResultArray(); return view('pohabispakai/index',['rows'=>$rows,'details'=>$details,'suppliers'=>(new ModelSupplier())->orderBy('supnama')->findAll(),'stok'=>(new ModelStokHabisPakai())->where('aktif',1)->orderBy('nama')->findAll()]); }
    public function simpan(){ if(!AccessControl::can('order.po_habis_pakai.input'))return $this->deny(); $supplier=(new ModelSupplier())->find($this->request->getPost('supplier_id')); $ids=(array)$this->request->getPost('stok_id');$qtys=(array)$this->request->getPost('qty_pesan');$harga=(array)$this->request->getPost('harga'); if(!$supplier||!$ids)return redirect()->back()->withInput()->with('error','Supplier dan minimal satu barang wajib diisi.'); $stok=(new ModelStokHabisPakai())->find($ids);$map=[];foreach($stok as $s)$map[$s['id']]=$s; $details=[];$total=0;$nomor='PO-BHP-'.date('YmdHis'); foreach($ids as $i=>$id){$q=(float)($qtys[$i]??0);if($q<=0||!isset($map[$id]))continue;$h=(float)($harga[$i]??0);$sub=$q*$h;$total+=$sub;$details[]=['stok_id'=>$id,'kode'=>$map[$id]['kode'],'nama'=>$map[$id]['nama'],'satuan'=>$map[$id]['satuan'],'qty_pesan'=>$q,'qty_diterima'=>0,'harga'=>$h,'subtotal'=>$sub];} if(!$details)return redirect()->back()->withInput()->with('error','Detail barang tidak valid.');$db=db_connect();$db->transStart();$poId=(new ModelPoHabisPakai())->insert(['nomor_po'=>$nomor,'tanggal_po'=>$this->request->getPost('tanggal_po')?:date('Y-m-d'),'supplier_id'=>$supplier['supid'],'supplier_nama'=>$supplier['supnama'],'status'=>'DIBUAT','catatan'=>trim((string)$this->request->getPost('catatan')),'created_by'=>(string)session()->get('userid'),'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],true);foreach($details as &$d)$d['po_id']=$poId;(new ModelDetailPoHabisPakai())->insertBatch($details);$db->transComplete();return redirect()->to('poHabisPakai/index')->with($db->transStatus()?'message':'error',$db->transStatus()?'PO Barang Habis Pakai berhasil dibuat.':'PO gagal dibuat.'); }
    public function terima(){ if(!AccessControl::can('order.po_habis_pakai.receive'))return $this->deny();$detailId=(int)$this->request->getPost('detail_id');$invoice=trim((string)$this->request->getPost('nomor_invoice'));$q=(float)$this->request->getPost('qty');if(!$detailId||$invoice===''||$q<=0)return redirect()->back()->with('error','Detail PO, Invoice, dan qty wajib diisi.');$db=db_connect();$d=(new ModelDetailPoHabisPakai())->find($detailId);if(!$d||$q>((float)$d['qty_pesan']-(float)$d['qty_diterima']))return redirect()->back()->with('error','Qty penerimaan melebihi sisa PO.');$s=(new ModelStokHabisPakai())->find($d['stok_id']);if(!$s)return redirect()->back()->with('error','Master stok tidak ditemukan.');$before=(float)$s['stok'];$after=$before+$q;$db->transStart();(new ModelStokHabisPakai())->update($s['id'],['stok'=>$after,'updated_at'=>date('Y-m-d H:i:s')]);(new ModelDetailPoHabisPakai())->update($detailId,['qty_diterima'=>(float)$d['qty_diterima']+$q]);(new ModelPenerimaanPoHabisPakai())->insert(['po_id'=>$d['po_id'],'detail_id'=>$detailId,'stok_id'=>$s['id'],'nomor_invoice'=>$invoice,'nomor_surat_jalan'=>trim((string)$this->request->getPost('nomor_surat_jalan'))?:null,'qty'=>$q,'diterima_oleh'=>(string)session()->get('userid'),'diterima_at'=>date('Y-m-d H:i:s')]);(new ModelLogStokHabisPakai())->insert(['stok_id'=>$s['id'],'po_keluar_id'=>null,'po_detail_id'=>null,'nomor_invoice'=>$invoice,'nomor_surat_jalan'=>trim((string)$this->request->getPost('nomor_surat_jalan'))?:null,'jenis'=>'MASUK','qty'=>$q,'stok_sebelum'=>$before,'stok_sesudah'=>$after,'user_id'=>(string)session()->get('userid'),'catatan'=>'Penerimaan PO BHP','created_at'=>date('Y-m-d H:i:s')]);$db->transComplete();return redirect()->back()->with($db->transStatus()?'message':'error',$db->transStatus()?'Penerimaan berhasil, stok bertambah.':'Penerimaan gagal.');}
}
